[package]
name = "start-match"
version = "0.2.4"
description = "Locks a Soloon lobby, flips it to RUNNING, opens the first turn."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "start_match"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["bolt-lang/idl-build"]
anchor-debug = ["bolt-lang/anchor-debug"]
custom-heap = []
custom-panic = []

[dependencies]
bolt-lang.workspace = true
game-config = { path = "../../components/game-config", features = ["cpi"] }
