[package]
name = "end-match"
version = "0.2.4"
description = "Tombstone assertion: GameConfig.status must be Finished. Called by the lobby program before distributing the pot."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "end_match"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["bolt-lang/idl-build"]
anchor-debug = ["bolt-lang/anchor-debug"]
custom-heap = []
custom-panic = []

[dependencies]
bolt-lang.workspace = true
game-config = { path = "../../components/game-config", features = ["cpi"] }
